### PR TITLE
Add action updater.

### PR DESCRIPTION
**Pull request by hugobuddel**
From https://github.com/marketplace/actions/github-actions-version-updater

### CODE REVIEW

**Review by teutoburg — APPROVED** [review]
Seems useful 👍 

Although I think it would be sufficient to have it only update for major versions of the actions, there seems to be an option for that. But let's see if this will now swamp us with PRs for every little patch in all those actions. Nah, should be fine like this ^^

**Comment by hugobuddel** [comment]
I've merged it! I moved the default timer from Sunday at midnight to Sunday at 16:00, which is in 4 minutes. On my watch at least, and it is never clear to me what watch github uses, but well. Let's see what happens.

**Comment by teutoburg** [comment]
> I've merged it! I moved the default timer from Sunday at midnight to Sunday at 16:00, which is in 4 minutes. On my watch at least, and it is never clear to me what watch github uses, but well. Let's see what happens.

Well, if it's UTC, then we should see it in 1 h...

**Comment by teutoburg** [comment]
Nothing yet 👀

**Comment by hugobuddel** [comment]
> Nothing yet 👀

It should indeed be UTC, but no action yet! They often fire a bit later I noticed, so maybe it will take a while.

**Pull request merged**
