### PR TITLE
Try to use tee to pipe to $GITHUB_STEP_SUMMARY

### PR DESCRIPTION
**Pull request by hugobuddel**
This should ensure the information is both available in the summary as well as in the logs.

E.g. in https://github.com/AstarVienna/ScopeSim/actions/runs/11007444291/job/30563361651 it is hard to figure out what version of fonttools is actually being used.

`>>` schmekt ein bißchen (aber eben nicht ganz) anders als Tee

### CODE REVIEW

**Comment by teutoburg** [comment]
Seems useful if it works, but it appears it doesn't do just that on Windows 😟

**Comment by teutoburg** [comment]
Also, do you know what's up with the markdown link checker here? The link it complains about works when I click on it normally, but has been failing here for a while. Sure "it doesn't matter", but it's annoying to see it every time...

**Comment by hugobuddel** [comment]
> Seems useful if it works, but it appears it doesn't do just that on Windows 😟

Meh :disappointed:..

For reference:
```
Run poetry update | tee -a $GITHUB_STEP_SUMMARY
  poetry update | tee -a $GITHUB_STEP_SUMMARY
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Tee-Object: D:\a\_temp\c30473e9-6861-4eb1-91ca-eb6663e246c6.ps1:2
Line |
   2 |  poetry update | tee -a $GITHUB_STEP_SUMMARY
     |                         ~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'FilePath' because it is null.

[Errno 22] Invalid argument
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
Error: Process completed with exit code 1.
```

Apparently this redirect to $GITHUB_STEP_SUMMARY never worked on Windows, because the windows runs do not show up in the summary, e.g. see https://github.com/AstarVienna/ScopeSim/actions/runs/11026739755 . But now it complains

**Comment by hugobuddel** [comment]
> Also, do you know what's up with the markdown link checker here? The link it complains about works when I click on it normally, but has been failing here for a while. Sure "it doesn't matter", but it's annoying to see it every time...

Yes, see https://github.com/AstarVienna/DevOps/issues/32 . I'll just remove one of the hackernews quotes.

**Comment by hugobuddel** [comment]
https://stackoverflow.com/questions/75400531/how-to-display-github-step-summary-on-github-actions-with-windows-latest

Apparently we should use `$env:GITHUB_STEP_SUMMARY` for windows. But would be nice if we could find a platform independent way of creating the summary.

**Comment by hugobuddel** [comment]
Forcing the steps to use bash works.

Using bash is fine right? As in, most users will not start ScopeSim using bash, and maybe starting ScopeSim this way will make some hypothetical problems disappear. But I cannot think of anything; maybe `os.environ` would be different or so?

I propose we use both `shell: bash` and `| tee -a` for all our action steps.

The Markdown test fails because #34 is not merged here.

**Comment by hugobuddel** [comment]
Yeah I did check that the output is now both in the summary and in the log itself.

It seems that this is the only occurrence of `$GITHUB_STEP_SUMMARY` where windows actually matters. Most usage of `$GITHUB_STEP_SUMMARY` is in workflows for publishing etc., which we only do on Ubuntu.

The only other use seems to be the notebook tests in ScopeSim, but those we currently only run for Ubuntu as well, see https://github.com/AstarVienna/ScopeSim/blob/main/.github/workflows/notebooks_dispatch.yml . Maybe we should run them again on Windows though.

**Pull request merged**
